#config/redis.yml
default:
  host: localhost
  port: ENV['REDIS_URL']
development:
  db: 0
  namespace: snowschoolers_development
test:
  db: 1
  namespace: snowschoolers_test
production:
  db: 2
  host: 192.168.1.100
  namespace: snowschoolers_production